name = "AAPP Theme"
description = "Theme used for AAPP.storm.vu"
homepage = "https://aapp.storm.vu"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.30.2"

authors = [
	{name = "Erik Baalhuis"},
	{name = "Michael Vasseur", homepage = "https://iaminteger.nl"},
]

[original]
	author = "Mart Pluijmaekers"
	homepage = "https://github.com/tuupke"
  repo = "https://github.com/GEHACK/NWERC-Site-2019"
